### ISSUE TITLE
Incorrect craftbukkit package relocation: NoClassDefFoundError: org/bukkit/craftbukkit/v1_21_R5/CraftServer

### ISSUE THREAD

**Issue by danirod12** [pl3xgaming/Purpur#1678]
### Spark link

https://spark.lucko.me/BEh0D3rdT3

### Stack trace

```
[21:05:05] [Server thread/WARN]: java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_21_R5/CraftServer
...
```

Code part work on both Spigot-1.21.6 and Paper-1.21.6-24 and NOT work on Purpur-1.21.6-2454:
```
import org.bukkit.craftbukkit.v1_21_R5.CraftServer;

public class ItemLoader1_21_R5 implements ItemLoader {
  private final IRegistryCustom.Dimension registryAccess = ((CraftServer)Bukkit.getServer()).getServer().ba();
}
```

### Agreements

- [x] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [x] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [x] My version of Minecraft is supported by Purpur.

### Other

Something wrong with purpur remapping that causes incorrect package translation. Works well on Paper, so supposet to should be working on purpur also.

**Comment by NONPLAYT** [comment]
wait for next upstream update

**Comment by granny** [comment]
fixed by https://github.com/PurpurMC/Purpur/commit/afcdf9bb72f88eb18266f5efd8c135904d82fd3d
